volumes:
  pg_data:
  static:

services:
  db:
    container_name: db
    image: postgres
    shm_size: 128mb
    env_file: ./backend/.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  migrator:
    container_name: migrator
    depends_on:
      - db
    build: ./backend/
    env_file: ./backend/.env
    entrypoint: ["uv", "run", "--no-dev", "alembic", "upgrade", "head"]

  pgweb:
    container_name: pgweb
    image: sosedoff/pgweb

  backend:
    container_name: backend
    depends_on:
      migrator:
        condition: service_completed_successfully
    build: ./backend/
    env_file: ./backend/.env
    environment:
      SERVER_HOST: "0.0.0.0"

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      args:
        BACKEND_SERVER_HOST: localhost
        BACKEND_SERVER_PORT: 8000
    volumes:
      - static:/static

  nginx:
    container_name: nginx
    depends_on:
      - backend
    build: ./infrastructure/nginx
    ports:
      - "8000:80"
    volumes:
      - static:/static
