[project]
name = "backend"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "pydantic-settings>=2.8.1",
    "sqlmodel>=0.0.24",
]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "ruff>=0.11.5",
]

[tool.mypy]
plugins = ["pydantic.mypy"]
explicit_package_bases = true
strict = true
check_untyped_defs = true
exclude = [".*/tests.*"]
