extend-exclude = [
]

line-length = 79
target-version = "py313"

[lint]
select = [
    "F",    # Pyflakes
    "E",    # pcodestyle
    "I",    # isort
    "N",    # pep8-naming
    "B",    # flake8-bugbear
    "A",    # flake8-builtins
    "COM",  # flake8-commas
    "C4",   # flake8-comprehensions
    "DJ",   # flake8-django
    "ISC",  # flake8-implicit-str-concat
    "ICN",  # flake8-import-conventions
    "T20",  # flake8-print
    "Q",    # flake8-quotes
    "RET",  # flake8-return
    "FIX",  # flake8-fixme
    "ERA",  # eradicate
]

ignore = [
    "PTH123",
    "F403",
    "FIX002"
]

[lint.isort]
known-first-party = [
]

force-sort-within-sections = true
order-by-type = false

[lint.flake8-quotes]
inline-quotes = "single"

[format]
quote-style = "single"
